PREFIX components: <http://example.com/eds-oml/vocabulary/Component#>
PREFIX aspects: <http://example.com/eds-oml/vocabulary/Aspects#>

SELECT ?component_set ?component_id ?component_name
WHERE {
  # Fetch component sets
  ?component_set a components:ComponentSet .

  # Fetch component
  ?component a components:Component .
  ?component_set components:Element ?component .
  ?component aspects:hasId ?component_id .
  ?component aspects:hasCanonicalName ?component_name .
}
