PREFIX component: <http://example.com/eds-oml/vocabulary/Component#>
PREFIX state_machine: <http://example.com/eds-oml/vocabulary/StateMachine#>
PREFIX activity: <http://example.com/eds-oml/vocabulary/Activity#>
PREFIX interface: <http://example.com/eds-oml/vocabulary/Interface#>
PREFIX aspects: <http://example.com/eds-oml/vocabulary/Aspects#>

SELECT ?component_set_id ?component_set_name ?component_id ?component_name ?state_machine_id ?activity_id ?interface_id
WHERE {
  # Fetch component sets
  ?component_set a component:ComponentSet .
  ?component_set aspects:hasId ?component_set_id .
  ?component_set aspects:hasCanonicalName ?component_set_name .

  # Fetch component
  ?component a component:Component .
  ?component aspects:hasId ?component_id .
  ?component aspects:hasCanonicalName ?component_name .

  # Fetch state machines defining the component
  OPTIONAL {
    ?component component:ComponentDefinedByStateMachine ?state_machine .
    ?state_machine aspects:hasId ?state_machine_id .
  }

  # Fetch activities contained in the component
  OPTIONAL {
    ?component component:ComponentContainsActivity ?activity .
    ?activity aspects:hasId ?activity_id .
  }

  # Fetch interfaces referenced by the component
  OPTIONAL {
    ?component component:ComponentReferencesInterface ?interface .
    ?interface aspects:hasId ?interface_id .
  }
}
ORDER BY ?component_set_id ?component_id ?state_machine_id ?activity_id ?interface_id
