PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX aspects: <http://example.com/eds-oml/vocabulary/Aspects#>
PREFIX dataSheet: <http://example.com/eds-oml/vocabulary/DataSheet#>
PREFIX device: <http://example.com/eds-oml/vocabulary/Device#>
PREFIX metadata: <http://example.com/eds-oml/vocabulary/Metadata#>
PREFIX package: <http://example.com/eds-oml/vocabulary/Package#>
PREFIX component: <http://example.com/eds-oml/vocabulary/Component#>
PREFIX interface: <http://example.com/eds-oml/vocabulary/Interface#>

SELECT ?device_id ?device_name ?metadata_id ?metadata_name
WHERE {
  # Get device details
  ?device a device:Device .
  ?device aspects:hasId ?device_id .
  ?device aspects:hasCanonicalName ?device_name .

  # Get associated metadata set
  OPTIONAL {
    ?device device:DeviceContainsMetadatas ?metadataSet .
    ?metadataSet metadata:CategoryOfMetadata ?categoryMetadata .
    ?categoryMetadata metadata:ElementOfCategory ?metadata .
    ?metadata aspects:hasId ?metadata_id .
    ?metadata aspects:hasCanonicalName ?metadata_name .
  }
}
ORDER BY ?device_id ?metadata_id
