PREFIX test2: <http://example.com/eds-oml/vocabulary/structure#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?device ?tension ?metadata
WHERE {
  ?device a test2:Device .
  OPTIONAL { ?device test2:hasTension ?tension . }
  OPTIONAL { 
    ?metadata test2:fromDevice ?device .
    ?metadata a test2:Metadata .
  }
}
